name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v5
    - run: cargo hack nextest run --release --all-targets --verbose --feature-powerset
    - run: cargo hack test --doc --release --all-features --verbose
  clippy:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v5
    - run: cargo hack clippy --release --all-targets --verbose --feature-powerset -- --deny warnings
  doc:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    env:
      RUSTDOCFLAGS: --deny warnings
    steps:
    - uses: actions/checkout@v5
    - run: cargo doc --no-deps --release --verbose --all-features
  semver:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v5
    - run: cargo semver-checks --verbose
  audit:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v5
    - run: cargo audit --deny warnings